#!/usr/bin/env python3
"""
generate.py — single source of truth expansion for VMwareStigAdapter

Reads rules/*.yaml and emits EVERY downstream artifact. Nothing it writes is
ever hand-edited; regenerate instead. A quarterly STIG revision becomes a
rules.yaml diff plus a regen, not a rewrite.

Outputs (all under --out):
    rule_registry.py        collector dispatch table (import into adapter)
    metric_defs.py          define_metric()/define_property() for adapter.py
    symptoms_alerts.xml     Aria symptom + alert definitions
    resources.properties    UI label strings
    scorecard.xml           custom compliance scorecard (Operations > Compliance)
    coverage.md             human review artifact — counts, phases, gaps

Usage:
    python3 scripts/generate.py rules/ --out generated/
    python3 scripts/generate.py rules/ --out generated/ --allow-unverified
"""

import argparse
import sys
from pathlib import Path
from xml.sax.saxutils import escape, quoteattr

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_rules import (load_all, ELEVATED_METHODS, SSH_METHODS,  # noqa: E402
                            Problem)

ADAPTER_KIND = "VMwareStigAdapter"

# Rule result encoding — see _SCHEMA.md. Symptom fires on == 0.
RESULT_OPEN = 0
RESULT_NOTAFINDING = 1
RESULT_NOT_APPLICABLE = 2
RESULT_NOT_REVIEWED = 3

CAT_SEVERITY = {1: "CRITICAL", 2: "IMMEDIATE", 3: "WARNING"}

# Native binding: vm_advanced_setting rules read vCommunity-collected
# properties off the NATIVE VirtualMachine object so the Compliance tab
# lights up on real VMs. Key format is fixed by vCommunity's collector
# (properties/vm/vm_extra_config.py): vm_obj.with_property(
#   f"vCommunity|Configuration|Advanced Parameters|{key}", value)
NATIVE_VM_ADAPTER_KIND = "VMWARE"
NATIVE_VM_RESOURCE_KIND = "VirtualMachine"
VCOMMUNITY_VM_ADV_PREFIX = "vCommunity|Configuration|Advanced Parameters|"

# STIG operator -> Aria symptom condition operator (string property compare)
_OP_MAP = {"equals": "EQ", "not_equals": "NE"}

# Stable rollups. Dashboards bind HERE, never to rule IDs.
ROLLUP_METRICS = [
    ("summary|score_pct",        "STIG Score (%)"),
    ("summary|findings_open",    "Open Findings"),
    ("summary|findings_actionable", "Open Findings (Actionable)"),
    ("summary|findings_accepted",   "Open Findings (Risk Accepted)"),
    ("summary|findings_cat1",    "CAT I Findings"),
    ("summary|findings_cat2",    "CAT II Findings"),
    ("summary|findings_cat3",    "CAT III Findings"),
    ("summary|not_applicable",   "Not Applicable"),
    ("summary|not_reviewed",     "Not Reviewed"),
    ("summary|rules_evaluated",  "Rules Evaluated"),
]

ROLLUP_PROPERTIES = [
    ("stig|benchmark_id",      "Benchmark"),
    ("stig|benchmark_version", "Benchmark Version"),
    ("stig|benchmark_status",  "Benchmark Status"),
    ("stig|target_version",    "Platform Version"),
    ("stig|last_scan",         "Last Scan"),
]

BANNER = "# GENERATED by scripts/generate.py — DO NOT EDIT. Regenerate from rules/*.yaml.\n"
XML_BANNER = "<!-- GENERATED by scripts/generate.py — DO NOT EDIT. Regenerate from rules/*.yaml. -->\n"


def _flatten(docs):
    """[(benchmark_dict, rule_dict), ...] in stable order."""
    out = []
    for _path, doc in docs:
        bm = doc["benchmark"]
        for rule in doc.get("rules", []):
            out.append((bm, rule))
    return out


def _kinds(pairs):
    seen = []
    for bm, _ in pairs:
        if bm["target_kind"] not in seen:
            seen.append(bm["target_kind"])
    return seen


def _phase(rule):
    m = rule["check_method"]
    if m == "manual":
        return "manual"
    if m in SSH_METHODS:
        return "3"
    if m in ELEVATED_METHODS:
        return "2"
    return "1"


# ---------------------------------------------------------------- registry
def gen_rule_registry(pairs) -> str:
    lines = [
        BANNER,
        '"""Collector dispatch table. Keyed by rule id."""\n',
        "\nRESULT_OPEN = 0",
        "RESULT_NOTAFINDING = 1",
        "RESULT_NOT_APPLICABLE = 2",
        "RESULT_NOT_REVIEWED = 3",
        "\nRULES = [",
    ]
    for bm, rule in pairs:
        entry = {
            "id": rule["id"],
            "benchmark": bm["id"],
            "benchmark_version": bm["version"],
            "benchmark_status": bm["status"],
            "target_kind": bm["target_kind"],
            "applies_to": rule.get("applies_to", bm["applies_to"]),
            "cat": rule["cat"],
            "title": rule["title"],
            "check_method": rule["check_method"],
            "check": rule.get("check", {}),
            "risk_acceptance": rule.get("risk_acceptance"),
            "operator": rule.get("operator"),
            "expected": rule.get("expected"),
            "default_when_absent": rule.get("default_when_absent"),
            "phase": _phase(rule),
            "verified": bool(rule.get("verified")),
        }
        lines.append(f"    {entry!r},")
    lines.append("]\n")
    lines.append("RULES_BY_ID = {r['id']: r for r in RULES}\n")
    lines.append("""
def rules_for(target_kind, platform_version):
    \"\"\"Rules applicable to one object kind on one platform version.

    Mixed-fleet dispatch: an 8.0 host evaluates only 8.0 rules, a 9.0 host
    only 9.0 rules, from the same registry and the same running collector.
    \"\"\"
    return [
        r for r in RULES
        if r["target_kind"] == target_kind
        and platform_version in r["applies_to"]
    ]
""")
    return "\n".join(lines)


# ------------------------------------------------------------ metric defs
def gen_metric_defs(pairs) -> str:
    lines = [
        BANNER,
        '"""define_metric()/define_property() calls for adapter.py.\n',
        "Import and call define_stig_schema(kind_obj, target_kind) inside",
        'get_adapter_definition() for each STIG object kind."""\n',
        "\nROLLUP_METRICS = [",
    ]
    for key, label in ROLLUP_METRICS:
        lines.append(f"    ({key!r}, {label!r}),")
    lines.append("]\n")
    lines.append("ROLLUP_PROPERTIES = [")
    for key, label in ROLLUP_PROPERTIES:
        lines.append(f"    ({key!r}, {label!r}),")
    lines.append("]\n")

    lines.append("RULE_METRICS = {")
    for kind in _kinds(pairs):
        lines.append(f"    {kind!r}: [")
        for bm, rule in pairs:
            if bm["target_kind"] != kind:
                continue
            label = f"{rule['id']} — {rule['title']}"
            lines.append(f"        ({rule['id']!r}, {label!r}),")
        lines.append("    ],")
    lines.append("}\n")

    lines.append('''
def define_stig_schema(kind, target_kind):
    """Declare the full metric/property surface for one STIG object kind."""
    for key, label in ROLLUP_METRICS:
        kind.define_metric(key, label)
    for key, label in ROLLUP_PROPERTIES:
        kind.define_string_property(key, label)
    for rule_id, label in RULE_METRICS.get(target_kind, []):
        kind.define_metric(f"rules|{rule_id}", label)
        kind.define_string_property(f"evidence|{rule_id}", f"{rule_id} — Observed")
''')
    return "\n".join(lines)


# --------------------------------------------------------- symptoms/alerts
def gen_symptoms_alerts(pairs) -> str:
    out = ['<?xml version="1.0" encoding="UTF-8"?>', XML_BANNER.strip(),
           '<AlertDefinitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">',
           "  <SymptomDefinitions>"]

    emitted = []
    for bm, rule in pairs:
        if rule["check_method"] == "manual":
            continue  # attested-only: metric slot, no symptom, no alert
        sid = f"Symptom-{ADAPTER_KIND}-{rule['id']}"
        aid = f"Alert-{ADAPTER_KIND}-{rule['id']}"
        emitted.append((aid, bm, rule))
        sev = CAT_SEVERITY[rule["cat"]]

        if rule["check_method"] == "vm_advanced_setting":
            # Native binding: read vCommunity property off the real VM.
            # Symptom fires (finding) when the collected value does NOT equal
            # the expected value. The property is only present when the setting
            # exists; default_when_absent governs the absent case (an absent
            # property simply won't match, so no symptom fires — which is
            # correct for notafinding, and handled by a companion symptom for
            # the inverted/open cases below).
            setting = rule["check"]["key"]
            prop_key = f"{VCOMMUNITY_VM_ADV_PREFIX}{setting}"
            op = rule.get("operator", "equals")
            expected = str(rule.get("expected", ""))
            # Finding = present AND value != expected  → operator NE on the property
            cond_op = "NE" if op == "equals" else "EQ"
            out.append(
                f'    <SymptomDefinition id={quoteattr(sid)} '
                f'name={quoteattr(f"{rule['id']} — {rule['title']}")} '
                f'adapterKind="{NATIVE_VM_ADAPTER_KIND}" '
                f'resourceKind="{NATIVE_VM_RESOURCE_KIND}" '
                f'waitCycles="1" cancelCycles="2">'
            )
            out.append(f'      <State severity="{sev}">')
            out.append(
                f'        <Condition xsi:type="ConditionProperty" '
                f'key={quoteattr(prop_key)} operator="{cond_op}" '
                f'value={quoteattr(expected)} valueType="STRING" '
                f'instanced="false" thresholdType="STATIC"/>'
            )
            out.append("      </State>")
            out.append("    </SymptomDefinition>")
        else:
            out.append(
                f'    <SymptomDefinition id={quoteattr(sid)} '
                f'name={quoteattr(f"{rule['id']} — {rule['title']}")} '
                f'adapterKind="{ADAPTER_KIND}" '
                f'resourceKind="{bm["target_kind"]}" '
                f'waitCycles="1" cancelCycles="2">'
            )
            out.append(f'      <State severity="{sev}">')
            out.append(
                f'        <Condition xsi:type="ConditionMetric" '
                f'key="rules|{rule["id"]}" operator="EQ" value="{RESULT_OPEN}" '
                f'valueType="NUMERIC" instanced="false" thresholdType="STATIC"/>'
            )
            out.append("      </State>")
            out.append("    </SymptomDefinition>")

    out.append("  </SymptomDefinitions>")

    for aid, bm, rule in emitted:
        sid = f"Symptom-{ADAPTER_KIND}-{rule['id']}"
        desc = (f"{rule['title']} "
                f"({bm['title']} {bm['version']}, CAT {'I' * rule['cat']})")
        if rule["check_method"] == "vm_advanced_setting":
            a_adapter, a_kind = NATIVE_VM_ADAPTER_KIND, NATIVE_VM_RESOURCE_KIND
        else:
            a_adapter, a_kind = ADAPTER_KIND, bm["target_kind"]
        out.append(
            f'  <AlertDefinition id={quoteattr(aid)} '
            f'name={quoteattr(f"{rule['id']} — {rule['title']}")} '
            f'adapterKind="{a_adapter}" '
            f'resourceKind="{a_kind}" '
            f'waitCycles="1" cancelCycles="2" type="19" subType="19">'
        )
        out.append(f"    <Description>{escape(desc)}</Description>")
        out.append('    <State severity="{}" impact="risk">'.format(
            CAT_SEVERITY[rule["cat"]]))
        out.append(f'      <SymptomSet operator="AND" applyOn="SELF">')
        out.append(f'        <Symptom id={quoteattr(sid)}/>')
        out.append("      </SymptomSet>")
        out.append("    </State>")
        out.append("  </AlertDefinition>")

    out.append("</AlertDefinitions>")
    return "\n".join(out) + "\n"


# ------------------------------------------------------------- properties
def gen_resources_properties(pairs) -> str:
    lines = ["# GENERATED by scripts/generate.py — DO NOT EDIT.", ""]
    for key, label in ROLLUP_METRICS + ROLLUP_PROPERTIES:
        lines.append(f"{key} = {label}")
    lines.append("")
    for bm, rule in pairs:
        lines.append(f"rules|{rule['id']} = {rule['id']} — {rule['title']}")
        lines.append(f"evidence|{rule['id']} = {rule['id']} — Observed Value")
    return "\n".join(lines) + "\n"


# -------------------------------------------------------------- scorecard
def gen_scorecard(pairs) -> str:
    by_bm = {}
    for bm, rule in pairs:
        if rule["check_method"] == "manual":
            continue
        by_bm.setdefault((bm["id"], bm["title"], bm["version"]), []).append(rule)

    out = ['<?xml version="1.0" encoding="UTF-8"?>', XML_BANNER.strip(),
           "<scorecardContent>", "  <ComplianceScorecards>"]
    for (bid, btitle, bver), rules in by_bm.items():
        name = f"{btitle} {bver}"
        out.append(f'    <ComplianceScorecard description={quoteattr(btitle)} '
                   f'name={quoteattr(name)} type="CUSTOM">')
        out.append("      <AlertDefinitionIds>")
        for rule in rules:
            out.append(f'        <AlertDefinitionId '
                       f'id="Alert-{ADAPTER_KIND}-{rule["id"]}"/>')
        out.append("      </AlertDefinitionIds>")
        out.append("    </ComplianceScorecard>")
    out.append("  </ComplianceScorecards>")
    out.append("</scorecardContent>")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------- coverage
def gen_coverage(pairs) -> str:
    lines = [
        "# STIG rule coverage report",
        "",
        "GENERATED — do not edit. Review artifact: this is what tells you whether",
        "the score denominator is honest. Deliberately timestamp-free so a regen",
        "with no rule changes produces an empty diff.",
        "",
    ]

    benches = {}
    for bm, rule in pairs:
        benches.setdefault((bm["id"], bm["title"], bm["version"], bm["status"]),
                           []).append(rule)

    lines += ["| Benchmark | Version | Status | Rules | P1 API | P2 esxcli | P3 SSH | Manual | Unverified |",
              "|---|---|---|---|---|---|---|---|---|"]
    for (bid, btitle, bver, bstatus), rules in benches.items():
        p1 = sum(1 for r in rules if _phase(r) == "1")
        p2 = sum(1 for r in rules if _phase(r) == "2")
        p3 = sum(1 for r in rules if _phase(r) == "3")
        man = sum(1 for r in rules if _phase(r) == "manual")
        unv = sum(1 for r in rules if not r.get("verified"))
        flag = " ⚠" if bstatus == "srg" else ""
        lines.append(f"| {bid} | {bver} | {bstatus}{flag} | {len(rules)} | "
                     f"{p1} | {p2} | {p3} | {man} | {unv} |")

    total = len(pairs)
    unverified = [r for _, r in pairs if not r.get("verified")]
    manual = [(b, r) for b, r in pairs if _phase(r) == "manual"]
    phase2 = [(b, r) for b, r in pairs if _phase(r) == "2"]
    phase3 = [(b, r) for b, r in pairs if _phase(r) == "3"]

    lines += [
        "",
        "## Gates",
        "",
        f"- **{len(unverified)} of {total} rules unverified.** These cannot ship "
        "without `--allow-unverified`. Verification means a human confirmed the "
        "rule ID and expected value against the published STIG.",
        f"- **{len(phase2)} rules need privileges above vCenter Read-only** "
        "(esxcli tier). These fail closed to Not_Reviewed if the service account "
        "lacks the role — they do not silently pass.",
        f"- **{len(phase3)} rules require appliance shell access (Phase 3).** "
        "This is a security decision, not a permissions one — VCSA-80-000303 "
        "requires VCSA SSH be disabled. If SSH is not permitted these must be "
        "reclassified as attested-only, never left to pass silently.",
        f"- **{len(manual)} rules are attested-only.** They hold a permanent "
        "Not_Reviewed metric slot so the denominator reflects the real baseline "
        "rather than only the automatable subset.",
        "",
        "## Attested-only rules",
        "",
    ]
    for bm, rule in manual:
        lines.append(f"- `{rule['id']}` — {rule['title']}")
        if rule.get("notes"):
            lines.append(f"  - {rule['notes'].strip()}")

    if phase3:
        lines += ["", "## Phase 3 (appliance shell access required)", ""]
        for bm, rule in phase3:
            lines.append(f"- `{rule['id']}` — {rule['title']}")

    accepted = [(b, r) for b, r in pairs if r.get("risk_acceptance")]
    if accepted:
        lines += ["", "## Documented risk acceptances", "",
                  "These still report **Open** and still count against the score.",
                  "The split exists so ops dashboards can show actionable work",
                  "without the score ever being inflated.", "",
                  "| Rule | Status | Reference | Rationale |",
                  "|---|---|---|---|"]
        for bm, rule in accepted:
            ra = rule["risk_acceptance"]
            rat = " ".join(str(ra.get("rationale", "")).split())
            if len(rat) > 90:
                rat = rat[:87] + "…"
            lines.append(f"| `{rule['id']}` | {ra.get('status')} | "
                         f"{ra.get('reference')} | {rat} |")

    lines += ["", "## Phase 2 (elevated privileges required)", ""]
    for bm, rule in phase2:
        c = rule.get("check", {})
        lines.append(f"- `{rule['id']}` — `esxcli {c.get('namespace')}` "
                     f"field `{c.get('field')}`")

    if any(b["status"] == "srg" for b, _ in pairs):
        lines += [
            "",
            "## ⚠ STIG Readiness Guide content present",
            "",
            "Benchmarks marked `srg` are pre-DISA-review. Control identifiers and "
            "severity ratings will be realigned when the official STIG publishes. "
            "Do not build dashboards or reports against these rule IDs — bind to "
            "the `summary|*` rollups, which are stable across revisions.",
        ]

    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------- main
def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("rules_dir", type=Path)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--allow-unverified", action="store_true",
                    help="emit content from rules that have not been confirmed "
                         "against the published STIG (development only)")
    args = ap.parse_args(argv)

    try:
        docs, errors = load_all(args.rules_dir,
                                require_verified=not args.allow_unverified)
    except Problem as exc:
        print(f"[GENERATE] FATAL — {exc}")
        return 2

    if errors:
        print(f"[GENERATE] ABORT — {len(errors)} validation error(s):")
        for err in errors[:40]:
            print(f"  ✗ {err}")
        if len(errors) > 40:
            print(f"  … and {len(errors) - 40} more")
        return 1

    pairs = _flatten(docs)
    args.out.mkdir(parents=True, exist_ok=True)

    artifacts = {
        "rule_registry.py":      gen_rule_registry(pairs),
        "metric_defs.py":        gen_metric_defs(pairs),
        "symptoms_alerts.xml":   gen_symptoms_alerts(pairs),
        "resources.properties":  gen_resources_properties(pairs),
        "scorecard.xml":         gen_scorecard(pairs),
        "coverage.md":           gen_coverage(pairs),
    }
    for name, body in artifacts.items():
        (args.out / name).write_text(body)

    kinds = _kinds(pairs)
    unverified = sum(1 for _, r in pairs if not r.get("verified"))
    print(f"[GENERATE] {len(pairs)} rule(s) across {len(kinds)} kind(s): "
          f"{', '.join(kinds)}")
    for name in artifacts:
        print(f"  → {args.out / name}")
    if unverified:
        print(f"[GENERATE] WARNING — {unverified} unverified rule(s) emitted "
              f"(--allow-unverified). NOT shippable.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
